import datetime
from django.utils.translation import gettext_lazy as _
from wagtail.images.blocks import ImageChooserBlock
from wagtail.embeds.blocks import EmbedBlock
from wagtail.contrib.table_block.blocks import TableBlock
from wagtail.contrib.typed_table_block.blocks import TypedTableBlock
from wagtail.blocks import BooleanBlock, CharBlock, ChoiceBlock, MultipleChoiceBlock, RichTextBlock, StreamBlock, StructBlock, TextBlock, RawHTMLBlock, ListBlock, PageChooserBlock, IntegerBlock, DateTimeBlock


countries=[
    ("AE","AE"),
    ("AF","AF"),
    ("AL","AL"),
    ("AM","AM"),
    ("AO","AO"),
    ("AR","AR"),
    ("AT","AT"),
    ("AU","AU"),
    ("AZ","AZ"),
    ("BA","BA"),
    ("BD","BD"),
    ("BE","BE"),
    ("BF","BF"),
    ("BG","BG"),
    ("BI","BI"),
    ("BJ","BJ"),
    ("BN","BN"),
    ("BO","BO"),
    ("BR","BR"),
    ("BS","BS"),
    ("BT","BT"),
    ("BW","BW"),
    ("BY","BY"),
    ("BZ","BZ"),
    ("CA","CA"),
    ("CD","CD"),
    ("CF","CF"),
    ("CG","CG"),
    ("CH","CH"),
    ("CI","CI"),
    ("CL","CL"),
    ("CM","CM"),
    ("CN","CN"),
    ("CO","CO"),
    ("CR","CR"),
    ("CU","CU"),
    ("CY","CY"),
    ("CZ","CZ"),
    ("DE","DE"),
    ("DJ","DJ"),
    ("DK","DK"),
    ("DO","DO"),
    ("DZ","DZ"),
    ("EC","EC"),
    ("EE","EE"),
    ("EG","EG"),
    ("EH","EH"),
    ("ER","ER"),
    ("ES","ES"),
    ("ET","ET"),
    ("FK","FK"),
    ("FI","FI"),
    ("FJ","FJ"),
    ("FR","FR"),
    ("GA","GA"),
    ("GB","GB"),
    ("GE","GE"),
    ("GF","GF"),
    ("GH","GH"),
    ("GL","GL"),
    ("GM","GM"),
    ("GN","GN"),
    ("GQ","GQ"),
    ("GR","GR"),
    ("GT","GT"),
    ("GW","GW"),
    ("GY","GY"),
    ("HN","HN"),
    ("HR","HR"),
    ("HT","HT"),
    ("HU","HU"),
    ("ID","ID"),
    ("IE","IE"),
    ("IL","IL"),
    ("IN","IN"),
    ("IQ","IQ"),
    ("IR","IR"),
    ("IS","IS"),
    ("IT","IT"),
    ("JM","JM"),
    ("JO","JO"),
    ("JP","JP"),
    ("KE","KE"),
    ("KG","KG"),
    ("KH","KH"),
    ("KP","KP"),
    ("KR","KR"),
    ("XK","XK"),
    ("KW","KW"),
    ("KZ","KZ"),
    ("LA","LA"),
    ("LB","LB"),
    ("LK","LK"),
    ("LR","LR"),
    ("LS","LS"),
    ("LT","LT"),
    ("LU","LU"),
    ("LV","LV"),
    ("LY","LY"),
    ("MA","MA"),
    ("MD","MD"),
    ("ME","ME"),
    ("MG","MG"),
    ("MK","MK"),
    ("ML","ML"),
    ("MM","MM"),
    ("MN","MN"),
    ("MR","MR"),
    ("MW","MW"),
    ("MX","MX"),
    ("MY","MY"),
    ("MZ","MZ"),
    ("NA","NA"),
    ("NC","NC"),
    ("NE","NE"),
    ("NG","NG"),
    ("NI","NI"),
    ("NL","NL"),
    ("NO","NO"),
    ("NP","NP"),
    ("NZ","NZ"),
    ("OM","OM"),
    ("PA","PA"),
    ("PE","PE"),
    ("PG","PG"),
    ("PH","PH"),
    ("PL","PL"),
    ("PK","PK"),
    ("PR","PR"),
    ("PS","PS"),
    ("PT","PT"),
    ("PY","PY"),
    ("QA","QA"),
    ("RO","RO"),
    ("RS","RS"),
    ("RU","RU"),
    ("RW","RW"),
    ("SA","SA"),
    ("SB","SB"),
    ("SD","SD"),
    ("SE","SE"),
    ("SI","SI"),
    ("SJ","SJ"),
    ("SK","SK"),
    ("SL","SL"),
    ("SN","SN"),
    ("SO","SO"),
    ("SR","SR"),
    ("SS","SS"),
    ("SV","SV"),
    ("SY","SY"),
    ("SZ","SZ"),
    ("TD","TD"),
    ("TF","TF"),
    ("TG","TG"),
    ("TH","TH"),
    ("TJ","TJ"),
    ("TL","TL"),
    ("TM","TM"),
    ("TN","TN"),
    ("TR","TR"),
    ("TT","TT"),
    ("TW","TW"),
    ("TZ","TZ"),
    ("UA","UA"),
    ("UG","UG"),
    ("US","US"),
    ("UY","UY"),
    ("UZ","UZ"),
    ("VE","VE"),
    ("VN","VN"),
    ("VU","VU"),
    ("YE","YE"),
    ("ZA","ZA"),
    ("ZM","ZM"),
    ("ZW","ZW")
]

class MapBlock(StructBlock):
  featured = MultipleChoiceBlock(choices=countries, default="", required=False, max_length=6, blank=True, null=True,  label="Featured Countires", help_text = "Choose Featured Countires")
  bg_c=CharBlock(required=False, max_length=28, blank=True, null=True, default="000", label="Fill Color", help_text = "Fill colors of all country")
  bg_c_f=CharBlock(required=False, max_length=28, blank=True, null=True, default="000", label="Featured Fill Color", help_text = "Fill colors of Featured Countries")
  bg_c_f_h=CharBlock(required=False, max_length=28, blank=True, null=True, default="000", label="Hover Fill Color", help_text = "Fill colors of Featured Countries During Mouse Hovering")
  b_clr=CharBlock(required=False, max_length=28, blank=True, null=True, default="000", label="Border Color", help_text = "border colors of all country")
  
  class Meta:  #noqa
    form_classname = "svg_map_glob struct_block"
    template = "blocks/map_glob.html"
    form_template = "block_forms/global_map_form.html"
    icon=""
    label="Map 🗺"
    group="SVG Object Blocks"